CREATE TABLE cms_prd.state_lookup (
    state_cd INT PRIMARY KEY,
    state_desc VARCHAR(100),
    state_abbr VARCHAR(2)
);

INSERT INTO cms_prd.state_lookup (state_cd, state_desc, state_abbr) VALUES
(1, 'Tennessee', 'TN'),
(2, 'Wyoming', 'WY'),
(3, 'Missouri', 'MO'),
(4, 'Alabama', 'AL'),
(5, 'California', 'CA'),
(6, 'Colorado', 'CO'),
(7, 'Nevada', 'NV'),
(8, 'Delaware', 'DE'),
(9, 'Vermont', 'VT'),
(10, 'Texas', 'TX'),
(11, 'New Jersey', 'NJ'),
(12, 'Montana', 'MT'),
(13, 'Hawaii', 'HI'),
(14, 'Ohio', 'OH'),
(15, 'Massachusetts', 'MA'),
(16, 'Puerto Rico', 'PR'),
(17, 'Kansas', 'KS'),
(18, 'South Carolina', 'SC'),
(19, 'Oklahoma', 'OK'),
(20, 'West Virginia', 'WV'),
(21, 'Kentucky', 'KY'),
(22, 'Arizona', 'AZ'),
(23, 'Georgia', 'GA'),
(24, 'Minnesota', 'MN'),
(25, 'Iowa', 'IA'),
(26, 'Indiana', 'IN'),
(27, 'South Dakota', 'SD'),
(28, 'Idaho', 'ID'),
(29, 'Nebraska', 'NE'),
(30, 'Maine', 'ME'),
(31, 'Michigan', 'MI'),
(32, 'Mississippi', 'MS'),
(33, 'New York', 'NY'),
(34, 'North Carolina', 'NC'),
(35, 'North Dakota', 'ND'),
(36, 'Illinois', 'IL'),
(37, 'Connecticut', 'CT'),
(38, 'Oregon', 'OR'),
(39, 'Pennsylvania', 'PA'),
(41, 'New Hampshire', 'NH'),
(42, 'Louisiana', 'LA'),
(43, 'Alaska', 'AK'),
(44, 'Washington', 'WA'),
(45, 'Florida', 'FL'),
(46, 'New Mexico', 'NM'),
(47, 'District of Columbia', 'DC'),
(49, 'Virginia', 'VA'),
(50, 'Wisconsin', 'WI'),
(51, 'Arkansas', 'AR'),
(52, 'Maryland', 'MD'),
(53, 'Rhode Island', 'RI'),
(54, 'Utah', 'UT');