CREATE TABLE cms_raw.carrier_claims (
    desynpuf_id VARCHAR(32),  -- Beneficiary Code (Foreign key reference to beneficiaries table)
    clm_id BIGINT PRIMARY KEY,  -- Claim ID
    clm_from_dt DATE,  -- Claims start date
    clm_thru_dt DATE,  -- Claims end date

    -- Claim Diagnosis Code 1 - Claim Diagnosis Code 8
    icd9_dgns_cd_1 VARCHAR(10),
    icd9_dgns_cd_2 VARCHAR(10),
    icd9_dgns_cd_3 VARCHAR(10),
    icd9_dgns_cd_4 VARCHAR(10),
    icd9_dgns_cd_5 VARCHAR(10),
    icd9_dgns_cd_6 VARCHAR(10),
    icd9_dgns_cd_7 VARCHAR(10),
    icd9_dgns_cd_8 VARCHAR(10),

    -- Provider Physician - National Provider Identifier Number
    prf_physn_npi_1 VARCHAR(15),
    prf_physn_npi_2 VARCHAR(15),
    prf_physn_npi_3 VARCHAR(15),
    prf_physn_npi_4 VARCHAR(15),
    prf_physn_npi_5 VARCHAR(15),
    prf_physn_npi_6 VARCHAR(15),
    prf_physn_npi_7 VARCHAR(15),
    prf_physn_npi_8 VARCHAR(15),
    prf_physn_npi_9 VARCHAR(15),
    prf_physn_npi_10 VARCHAR(15),
    prf_physn_npi_11 VARCHAR(15),
    prf_physn_npi_12 VARCHAR(15),
    prf_physn_npi_13 VARCHAR(15),

    -- Provider Institution Tax Number
    tax_num_1 VARCHAR(10),
    tax_num_2 VARCHAR(10),
    tax_num_3 VARCHAR(10),
    tax_num_4 VARCHAR(10),
    tax_num_5 VARCHAR(10),
    tax_num_6 VARCHAR(10),
    tax_num_7 VARCHAR(10),
    tax_num_8 VARCHAR(10),
    tax_num_9 VARCHAR(10),
    tax_num_10 VARCHAR(10),
    tax_num_11 VARCHAR(10),
    tax_num_12 VARCHAR(10),
    tax_num_13 VARCHAR(10),

    -- Line HCFA Common Procedure Coding System 1 - Line HCFA Common Procedure Coding System 13
    hcpcs_cd_1 VARCHAR(10),
    hcpcs_cd_2 VARCHAR(10),
    hcpcs_cd_3 VARCHAR(10),
    hcpcs_cd_4 VARCHAR(10),
    hcpcs_cd_5 VARCHAR(10),
    hcpcs_cd_6 VARCHAR(10),
    hcpcs_cd_7 VARCHAR(10),
    hcpcs_cd_8 VARCHAR(10),
    hcpcs_cd_9 VARCHAR(10),
    hcpcs_cd_10 VARCHAR(10),
    hcpcs_cd_11 VARCHAR(10),
    hcpcs_cd_12 VARCHAR(10),
    hcpcs_cd_13 VARCHAR(10),

    -- Line NCH Payment Amount 1 - Line NCH Payment Amount 13
    line_nch_pmt_amt_1 FLOAT,
    line_nch_pmt_amt_2 FLOAT,
    line_nch_pmt_amt_3 FLOAT,
    line_nch_pmt_amt_4 FLOAT,
    line_nch_pmt_amt_5 FLOAT,
    line_nch_pmt_amt_6 FLOAT,
    line_nch_pmt_amt_7 FLOAT,
    line_nch_pmt_amt_8 FLOAT,
    line_nch_pmt_amt_9 FLOAT,
    line_nch_pmt_amt_10 FLOAT,
    line_nch_pmt_amt_11 FLOAT,
    line_nch_pmt_amt_12 FLOAT,
    line_nch_pmt_amt_13 FLOAT,
	
	-- Line Beneficiary Part B Deductible Amount 1 - Line Beneficiary Part B Deductible Amount 13
    line_bene_ptb_ddctbl_amt_1 FLOAT,
    line_bene_ptb_ddctbl_amt_2 FLOAT,
    line_bene_ptb_ddctbl_amt_3 FLOAT,
    line_bene_ptb_ddctbl_amt_4 FLOAT,
    line_bene_ptb_ddctbl_amt_5 FLOAT,
    line_bene_ptb_ddctbl_amt_6 FLOAT,
    line_bene_ptb_ddctbl_amt_7 FLOAT,
    line_bene_ptb_ddctbl_amt_8 FLOAT,
    line_bene_ptb_ddctbl_amt_9 FLOAT,
    line_bene_ptb_ddctbl_amt_10 FLOAT,
    line_bene_ptb_ddctbl_amt_11 FLOAT,
    line_bene_ptb_ddctbl_amt_12 FLOAT,
    line_bene_ptb_ddctbl_amt_13 FLOAT,
	
	-- Line Beneficiary Primary Payer Paid Amount 1 - Line Beneficiary Primary Payer Paid Amount 13
    line_bene_prmry_pyr_pd_amt_1 FLOAT,
    line_bene_prmry_pyr_pd_amt_2 FLOAT,
    line_bene_prmry_pyr_pd_amt_3 FLOAT,
    line_bene_prmry_pyr_pd_amt_4 FLOAT,
    line_bene_prmry_pyr_pd_amt_5 FLOAT,
    line_bene_prmry_pyr_pd_amt_6 FLOAT,
    line_bene_prmry_pyr_pd_amt_7 FLOAT,
    line_bene_prmry_pyr_pd_amt_8 FLOAT,
    line_bene_prmry_pyr_pd_amt_9 FLOAT,
    line_bene_prmry_pyr_pd_amt_10 FLOAT,
    line_bene_prmry_pyr_pd_amt_11 FLOAT,
    line_bene_prmry_pyr_pd_amt_12 FLOAT,
    line_bene_prmry_pyr_pd_amt_13 FLOAT,
	
	-- Line Coinsurance Amount 1 - Line Coinsurance Amount 13
	line_coinsrnc_amt_1 FLOAT,
	line_coinsrnc_amt_2 FLOAT,
	line_coinsrnc_amt_3 FLOAT,
	line_coinsrnc_amt_4 FLOAT,
	line_coinsrnc_amt_5 FLOAT,
	line_coinsrnc_amt_6 FLOAT,
	line_coinsrnc_amt_7 FLOAT,
	line_coinsrnc_amt_8 FLOAT,
	line_coinsrnc_amt_9 FLOAT,
	line_coinsrnc_amt_10 FLOAT,
	line_coinsrnc_amt_11 FLOAT,
	line_coinsrnc_amt_12 FLOAT,
	line_coinsrnc_amt_13 FLOAT,
	
	-- Line Allowed Charge Amount 1 - Line Allowed Charge Amount 13
	line_alowd_chrg_amt_1 FLOAT,
	line_alowd_chrg_amt_2 FLOAT,
	line_alowd_chrg_amt_3 FLOAT,
	line_alowd_chrg_amt_4 FLOAT,
	line_alowd_chrg_amt_5 FLOAT,
	line_alowd_chrg_amt_6 FLOAT,
	line_alowd_chrg_amt_7 FLOAT,
	line_alowd_chrg_amt_8 FLOAT,
	line_alowd_chrg_amt_9 FLOAT,
	line_alowd_chrg_amt_10 FLOAT,
	line_alowd_chrg_amt_11 FLOAT,
	line_alowd_chrg_amt_12 FLOAT,
	line_alowd_chrg_amt_13 FLOAT,

    -- Line Processing Indicator Code 1 - Line Processing Indicator Code 13
    line_prcsg_ind_cd_1 VARCHAR(5),
    line_prcsg_ind_cd_2 VARCHAR(5),
    line_prcsg_ind_cd_3 VARCHAR(5),
    line_prcsg_ind_cd_4 VARCHAR(5),
    line_prcsg_ind_cd_5 VARCHAR(5),
    line_prcsg_ind_cd_6 VARCHAR(5),
    line_prcsg_ind_cd_7 VARCHAR(5),
    line_prcsg_ind_cd_8 VARCHAR(5),
    line_prcsg_ind_cd_9 VARCHAR(5),
    line_prcsg_ind_cd_10 VARCHAR(5),
    line_prcsg_ind_cd_11 VARCHAR(5),
    line_prcsg_ind_cd_12 VARCHAR(5),
    line_prcsg_ind_cd_13 VARCHAR(5),

    -- Line Diagnosis Code 1 - Line Diagnosis Code 13
    line_icd9_dgns_cd_1 VARCHAR(10),
    line_icd9_dgns_cd_2 VARCHAR(10),
    line_icd9_dgns_cd_3 VARCHAR(10),
    line_icd9_dgns_cd_4 VARCHAR(10),
    line_icd9_dgns_cd_5 VARCHAR(10),
    line_icd9_dgns_cd_6 VARCHAR(10),
    line_icd9_dgns_cd_7 VARCHAR(10),
    line_icd9_dgns_cd_8 VARCHAR(10),
    line_icd9_dgns_cd_9 VARCHAR(10),
    line_icd9_dgns_cd_10 VARCHAR(10),
    line_icd9_dgns_cd_11 VARCHAR(10),
    line_icd9_dgns_cd_12 VARCHAR(10),
    line_icd9_dgns_cd_13 VARCHAR(10)
);